### ISSUE TITLE
Typos in AISParser.cs

### ISSUE THREAD

**Issue by ClemensFischer** [gcapnias/SharpAIS#1]
Hello George, just found your SharpAIS library very helpful.
I've noticed the typos "Lattitude" and "Lontitude" in AISParser.cs. Before forking and creating a pull request I though I'd better ask you if you could perhaps fix that in the master repository.
Ευχαριστώ πολύ!
Clemens

**Comment by gcapnias** [comment]
Hello Clemens!

I have just updated the project, to the latest version of the parser I have. There are a lot of fixes and the correction of the typos.

Regards,
George J.

**Comment by ClemensFischer** [comment]
Thanks a lot!

**Comment by gcapnias** [comment]
Hi Clemens,

This is an ongoing project for me this period. Any help/feedback on validating the parser, would be appreciated!


Regard,
George J.
