### ISSUE TITLE
The type or namespace name 'Parser' could not be found

### ISSUE THREAD

**Issue by Ali-Gubran** [gcapnias/SharpAIS#2]
hello 
in SharpAIS.DotSpatialMap AISHelper  class
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Parser' could not be found (are you missing a using directive or an assembly reference?)	SharpAIS.DotSpatialMap	E:\Projects\TestProjects\SharpAIS-master\SharpAIS.DotSpatial\AISHelper.cs	21	N/A

**Comment by gcapnias** [comment]
Hello,

You need to build "SharpAIS" before you can use "SharpAIS.DotSpatialMap".

I am under the impression that such an issue was fixed in a previous update. Did you get the latest release of code from the repository?


Cheers,
George J.
